### ISSUE TITLE
fix issue with "sign in" for Linkedin

### ISSUE THREAD

**Issue by jakub-pomykala** [OpenLiberty/quick-labs#288] opened 2021-01-21 14:55 UTC
When a user logins in using Linkedin and instead of creating a new account presses "sign in" (temporarily disabled) it doesn't render properly.

**Comment by austin0** [comment] 2021-04-09 10:48
Closing as duplicate of https://github.com/OpenLiberty/cloud-hosted-guides/issues/314.

**Closed as completed by austin0** 2021-04-09 10:48 UTC
Labels: enhancement
